//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace BlogsDomainEFModelFirst
{
    public partial class Blog
    {
        public Blog()
        {
            this.Posts = new HashSet<Post>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string BloggerName { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual ICollection<Post> Posts { get; set; }
    }
    
}
