    $("td a").click(function () {
        // ...
    });
    // objectivo - fazer callback para ir buscar detais, e depois, fazer com que details sejam editaveis, e ok ou cancel na edicao
    // fazer com que apareca uma linha com inputs editaveis, e esconder a linha de leitura...
